#!/bin/sh
echo Starting......
echo pwd.....
pwd
echo files....
ls
echo content of /artillery/loadconfig.yaml....
cat /artillery/loadconfig.yaml
echo running test
artillery run /artillery/loadconfig.yaml
echo Done.....
while [ true ]
do
   #echo keep runnig...
done
echo this should no be print!!!