apiVersion: v1 
kind: Pod
metadata:
  name: artillery
spec:
      containers:
      - name: artillery
        image: paraspatidardocker/artillery-manual
        ports:
        - containerPort: 80
        command: [ "sh", "-c", "artilleryRun" ]
        #args: [ "while true; do sleep 40; done;" ]